"""Cybersecurity Newsletter Editor Agent

A Bindu agent that researches the latest cybersecurity news, CVEs, and threat
intelligence, then drafts a professional newsletter section in Markdown.

Features:
- Live web search for recent threats, CVEs, and data breaches
- Structured newsletter output with sections for threats, CVEs, news, and recommendations
- Customizable by topic, time period, or threat category
- OpenRouter integration with gpt-oss-120b

Usage:
    python cybersecurity_newsletter_agent.py

Environment:
    Requires OPENROUTER_API_KEY in .env file

Example prompts:
    - "Write a cybersecurity newsletter for this week"
    - "Summarize the latest ransomware threats for a newsletter"
    - "Create a newsletter section about recent CVEs in Linux"
"""

import os
from dotenv import load_dotenv

load_dotenv()

from bindu.penguin.bindufy import bindufy
from agno.agent import Agent
from agno.models.openrouter import OpenRouter
from agno.tools.duckduckgo import DuckDuckGoTools

# ---------------------------------------------------------------------------
# Validate environment
# ---------------------------------------------------------------------------
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
if not OPENROUTER_API_KEY:
    raise RuntimeError(
        "OPENROUTER_API_KEY is not set. "
        "Copy .env.example to .env and add your OpenRouter API key."
    )

# ---------------------------------------------------------------------------
# Agent Definition
# ---------------------------------------------------------------------------
agent = Agent(
    name="Cybersecurity Newsletter Editor",
    instructions="""
    You are an expert Cybersecurity Newsletter Editor with deep knowledge of:
    - Threat intelligence and threat actor activity
    - CVEs (Common Vulnerabilities and Exposures)
    - Data breaches and ransomware campaigns
    - Security best practices and defensive recommendations

    TASK:
    When given a topic, time period, or free-form request, you will:
    1. Search the web for the latest relevant cybersecurity news and CVEs
    2. Synthesize findings into a professional, structured newsletter section

    OUTPUT FORMAT (always use this exact structure):

    # 🔐 Cybersecurity Newsletter — [Topic/Date]

    ## 🔥 Top Threats This Week
    - Brief bullet points on the most critical active threats
    - Include threat actor names, targeted sectors, and attack vectors

    ## 🛡️ CVE Spotlight
    - List 2–3 high-severity CVEs with: CVE ID, affected software, CVSS score, and patch status
    - Format: **CVE-YYYY-XXXXX** | Affected: `software` | CVSS: `score` | Status: `patched/unpatched`

    ## 📰 News Digest
    - 3–5 short summaries of notable cybersecurity news items
    - Each item: bold headline + 1–2 sentence summary + source link if available

    ## ✅ Recommendations
    - 3–5 actionable recommendations for security teams based on this week's threats
    - Keep them practical and specific

    ---
    *Newsletter generated by Cybersecurity Newsletter Editor — powered by Bindu*

    RULES:
    - Always search the web before writing — do not rely on training data for current events
    - Keep language professional but accessible (assume a mixed technical/non-technical audience)
    - If no specific topic is given, cover the most significant threats from the past 7 days
    - Always include at least one CVE and one data breach or ransomware item if available
    - Return clean Markdown only — no JSON wrappers, no code fences around the newsletter
    """,
    model=OpenRouter(
        id="openai/gpt-oss-120b",
        api_key=OPENROUTER_API_KEY,
    ),
    tools=[DuckDuckGoTools()],
    markdown=True,
)

# ---------------------------------------------------------------------------
# Bindu Configuration
# ---------------------------------------------------------------------------
config = {
    "author": "your.email@example.com",
    "name": "cybersecurity-newsletter-editor",
    "description": (
        "An AI-powered cybersecurity newsletter editor that researches the latest "
        "threats, CVEs, and security news, then drafts a structured newsletter section."
    ),
    "deployment": {
        "url": "http://localhost:3773",
        "expose": True,
        "cors_origins": ["http://localhost:5173"],
    },
    "skills": [
        "skills/question-answering",
        "skills/summarization",
    ],
}

# ---------------------------------------------------------------------------
# Handler Function
# ---------------------------------------------------------------------------
def handler(messages: list[dict[str, str]]):
    """Process messages and return agent response.

    Args:
        messages: List of message dictionaries containing conversation history.
                  Each message has 'role' ('user'|'assistant') and 'content' keys.

    Returns:
        Agent response with the drafted newsletter section in Markdown.
    """
    result = agent.run(input=messages)
    return result


# ---------------------------------------------------------------------------
# Start the agent with Bindu
# ---------------------------------------------------------------------------
bindufy(config, handler)

# To expose your agent to the internet via tunnel (local dev only):
# bindufy(config, handler, launch=True)
